### ISSUE TITLE
Using Automapper for Ionic 3 

### ISSUE THREAD

**Issue by savanvadalia** [loedeman/AutoMapper#28]
Hi @loedeman 

Thanks for creating this wonderful library, can't wait to use it in my project.

I am creating a hybrid mobile app using ionic framework which is based on typescript and would like to use this library in my project.

1) I would like to know what are the steps for using this library in a ionic project. I have just installed library from npm, not sure how to go forward from here
2) Ideally, with 3rd party Javascript/Typescript libraries it has @types to be installed for intellisense support.  Do you have @types for this library?

**Comment by loedeman** [comment]
Hi @savanvadalia,

You are welcome ;) , I hope you will enjoy using the library!

1. This library is a so-called classic library, not directly created with module systems in mind (the current ones weren't there at the moment of creation :) ). In order to use AutomapperTS in your project, you should manually load the automapper-ts file `./dist/automapper.js`, after which a global variable `automapper` will be available. I have created some kind of walkthrough about using the library in an Angular 2+ project here: https://github.com/loedeman/AutoMapper/issues/17 (it probably helps you as well).
2. The @types registration should have worked, because I committed the definition file to the DefinitelyTyped repo. However, it seems that library is pruning libraries based on world usage. I am afraid AutoMapperTS is not thát heavily used, compared to libraries like Angular, JQuery etc. etc. You can manually refer to the typings though: it is located in the `./dist/automapper.d.ts` folder.

I hope this helps you starting enjoying AutoMapperTS ;) !

**Comment by jboarman-ap** [comment]
Hi @savanvadalia, Were you ever able to figure this out?  I've gone through the steps as well and there is no _typings.d.ts_ file to `declare module 'automapper-ts';`.  I've tried wiring this is using `typeRoots` within _tsconfig.json_, but I'm still missing something.

**Comment by asanchez128** [comment]
My two cents to this conversation:

In your tsconfig.json file make sure that you have the right path for your typings.d.ts file

> "typeRoots": [
>       "node_modules/@types",
>       "../src/typings.d.ts"
>     ],
